### ISSUE TITLE
Sort #1 Level 100 sort by most recent posted

### ISSUE THREAD

**Issue by JDysiewicz** [CodeYourFuture/ldn8-horizon-chatterbox-talent#15]
Sorting was a non-client requirement, however we deemed it to provide very useful UX.

The following were agreed to be potentially useful sorting categories:

By scheme start-date (note - this field may not be easily retrievable given the existing fields)
By date added to the site
By duration of the program

Add sort drop down
Identify data to sort
on select opportunities are sorted

**Comment by craig-dsilva** [comment]
Done with API data
