### ISSUE TITLE
Add render state for results into redux

### ISSUE THREAD

**Issue by JDysiewicz** [CodeYourFuture/ldn8-horizon-chatterbox-talent#26]
Currently, we are displaying the results of the API call onto the screen. When we are applying searching/filtering, we wish to keep a semantic difference between the API result and the currently rendered subset of that data (that way, we can revert to original state without having to re-call the API).

Therefore, this would involve creating another entry in the redux store which represents the currently displayed programs based on the current filter/sort/search selection.

**Comment by mandeepsangha** [comment]
we saved it in State
