### ISSUE TITLE
Create filtering mock-up

### ISSUE THREAD

**Issue by JDysiewicz** [CodeYourFuture/ldn8-horizon-chatterbox-talent#6]
As we will have a large number of filters, we ought to be on the same page about how these filters will appear on the page

e.g. 

![Image](https://user-images.githubusercontent.com/49273611/177013164-aa76cec9-0569-4d89-bdfd-682fe87da3ec.png)

![Image](https://user-images.githubusercontent.com/49273611/177013189-3513c79d-fa65-4cdc-981f-42b621dd2f2c.png)

for some examples of different ways of displaying filters on a page.

**Comment by JDysiewicz** [comment]
note, the client has expressed that the cities/career types could scale massively, and so we should make sure the filter design could account for this (e.g. https://mui.com/material-ui/react-select/#checkmarks as an example)

**Comment by RitaGlushkova** [comment]
Figma board link to two options: 
1. Scroll with "Show more.." / "Show less.." buttons
[https://www.figma.com/file/wmKafFXESlx4ubDkRPpZlB/Wireframing-(Copy)?node-id=77%3A432](url)
2. Drop-down menu with checkboxes - recommended using this one by Janita (UX designer)
